policies:
  - name: "KerasPolicy"
    epochs: 10
    batch_size: 10
    validation_split: 0.2
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer
  - name: "MemoizationPolicy"
    max_history: 5
